server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/users_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112233
  rabbitmq:
    virtual-host: fwbqbdnc
    host: gerbil-01.rmq.cloudamqp.com
    port: 5672
    username: fwbqbdnc
    password: IraMUuhVfAPyy9KSt4v1YFZgY1_QyjoO
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
rabbitmq:
  exchange:
    name: socialmono_exchange
  routing:
    key: socialmono_routing_key
  queue:
    newsfeed:
      service:
        name: user_service_queue
      backend:
        name: user_backend_queue
    auth:
      service:
        name: auth_service_queue
      backend:
        name: auth_backend_queue