server:
  port: 8081
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://socialmono.c2qn2ku5pguw.ap-southeast-2.rds.amazonaws.com:3306/socialmono?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 11223344
