version: "3"
services:
  consul:
    image: consul:1.15.4
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
  newsfeed_db:
    container_name: newsfeeddb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=newsfeed
    ports:
      - "3306:3306"
    volumes:
      - newsfeedvol:/var/lib/mysql
  user_db:
    container_name: userdb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=usersdb
    ports:
      - "3307:3306"
    volumes:
      - uservol:/var/lib/mysql
volumes:
  newsfeedvol:
  uservol: