version: "3"
services:
  consul_server:
    container_name: consul_server
    build: ./docker/consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      - socialmono_network
  newsfeed_db:
    container_name: newsfeed_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=newsfeed_db
    ports:
      - "3306:3306"
    networks:
      - socialmono_network
    volumes:
      - newsfeed_vol:/var/lib/mysql
  user_db:
    container_name: user_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=users_db
    ports:
      - "3307:3306"
    networks:
      - socialmono_network
    volumes:
      - user_vol:/var/lib/mysql
  minio_storage:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3storage:/data
    environment:
      - MINIO_ROOT_USER=tinhtute
      - MINIO_ROOT_PASSWORD=vodichtoanvutru
      - MINIO_ACCESS_KEY=2toxGr9rkiDV77KG
      - MINIO_SECRET_KEY=b1lnyNTlc0FJECAxCE4phPYrSKLcpx9G
    command: server --console-address ":9001" /data
volumes:
  newsfeed_vol:
  user_vol:
  s3storage:
networks:
  socialmono_network:
    driver: bridge