version: "3"
services:
  consul:
    container_name: consul_server
    build: ./docker/consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      - socialmono_network
  newsfeed_db:
    container_name: newsfeed_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=newsfeed_db
    ports:
      - "3306:3306"
    networks:
      - socialmono_network
    volumes:
      - newsfeed_vol:/var/lib/mysql
  user_db:
    container_name: user_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=users_db
    ports:
      - "3307:3306"
    networks:
      - socialmono_network
    volumes:
      - user_vol:/var/lib/mysql
  minio_storage:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3storage:/data
    environment:
      - MINIO_ROOT_USER=tinhtute
      - MINIO_ROOT_PASSWORD=vodichtoanvutru
      - MINIO_ACCESS_KEY=2toxGr9rkiDV77KG
      - MINIO_SECRET_KEY=b1lnyNTlc0FJECAxCE4phPYrSKLcpx9G
    command: server --console-address ":9001" /data
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - socialmono_network
    volumes:
      - redis_vol:/data
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - socialmono_network
  mongo-express:
    image: mongo-express
    container_name: mongodb_admin
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
    networks:
      - socialmono_network
volumes:
  newsfeed_vol:
  user_vol:
  s3storage:
  redis_vol:
  mongo:
networks:
  socialmono_network:
    driver: bridge