server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**, /api/**
        - id: newsfeed
          uri: lb://newsfeed-service
          predicates:
            - Path=/newsfeed/**, /api/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /**