server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  config:
    import: consul:localhost:8500
  cloud:
    consul:
      config:
        format: yaml
        data-key: application
        enabled: true
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true