server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/**
        - id: newsfeed
          uri: lb://newsfeed-service
          predicates:
            - Path=/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/**
      default-filters:
        - AuthFilter
application:
  security:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1