server:
  port: 8082
spring:
  application:
    name: newsfeed-service
  cloud:
    consul:
      host: localhost
      port: 8500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql:/localhost:3307/socialmonodb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 11223344
  rabbitmq:
    virtual-host: fwbqbdnc
    host: gerbil-01.rmq.cloudamqp.com
    port: 5672
    username: fwbqbdnc
    password: IraMUuhVfAPyy9KSt4v1YFZgY1_QyjoO
rabbitmq:
  exchange:
    name: socialmono_exchange
  routing:
    key: socialmono_routing_key
  queue:
    service:
      name: user_service_queue
    backend:
      name: user_backend_queue