server:
  port: 8083
spring:
  application:
    name: auth-service
  cloud:
    consul:
      host: localhost
      port: 8500
  rabbitmq:
    virtual-host: fwbqbdnc
    host: gerbil-01.rmq.cloudamqp.com
    port: 5672
    username: fwbqbdnc
    password: IraMUuhVfAPyy9KSt4v1YFZgY1_QyjoO
rabbitmq:
  exchange:
    name: socialmono_exchange
  routing:
    key: socialmono_routing_key
  queue:
    service:
      name: auth_service_queue
    backend:
      name: auth_backend_queue
application:
  security:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    accessTokenExpiration: 86400000
    refreshTokenExpiration: 2592000000