server:
  port: 8090
spring:
  application:
    name: media-service
  cloud:
    consul:
      host: localhost
      port: 8500
  minio:
    endpoint: http://localhost:9000
    bucket:
      avatar: avatar
      post: post
    accessKey: tinhtute
    secretKey: vodichtoanvutru
application:
  rabbitmq:
    virtual-host: fwbqbdnc
    host: gerbil-01.rmq.cloudamqp.com
    port: 5672
    username: fwbqbdnc
    password: IraMUuhVfAPyy9KSt4v1YFZgY1_QyjoO
rabbitmq:
  exchange:
    name: socialmono_exchange
  routing:
    key: socialmono_routing_key
  queue:
    service:
      name: media_service_queue
    backend:
      name: media_backend_queue