server:
  port: 8090
spring:
  application:
    name: media-service
  config:
    import: consul:localhost:8500
  cloud:
    consul:
      config:
        format: yaml
        data-key: application
        enabled: true
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true